---
- name: Creating new LVM volume group(s)
  become: true
  lvg:
    vg: "{{ vg.vgname }}"
    pvs: "{{ vg.disks | join(',') }}"
    state: present
  when:
    - vg.create is defined
    - vg.create|bool

- name: Loop over logical volume group(s) to create logical volumes
  include_tasks: create_lv.yml
  loop: "{{ vg.lvnames | default([]) }}"
  loop_control:
    loop_var: lv
